### ISSUE TITLE
Include `id` property on the `RoadEventFeature` to better conform to GeoJSON

### ISSUE THREAD

**Issue by j-d-b** [usdot-jpo-ode/wzdx#141]
## Background
When reviewing the entire spec while refactoring to follow an object model, I came across this quote from [section 3.2 of the GeoJSON specification](https://tools.ietf.org/html/rfc7946#section-3.2):

> If a Feature has a commonly used identifier, that identifier SHOULD be included as a member of the Feature object with the name "id", and the value of this member is either a JSON string or number.

In the WZDx realm, road event's all have IDs, provided on the `road_event_id` field on the [RoadEvent](https://github.com/usdot-jpo-ode/jpo-wzdx/blob/master/spec-content/objects/RoadEvent.md) object. The `RoadEvent` object is used by the [RoadEventFeature](https://github.com/usdot-jpo-ode/jpo-wzdx/blob/master/spec-content/objects/RoadEventFeature.md) object, which is an instance of a GeoJSON Feature.

## Issue
The current WZDx specification details GeoJSON features that have an ID, however the ID is not included as an `id` field on the Feature itself and thus does not follow the GeoJSON specification.

## Solution
To better follow the GeoJSON specification, the road event's ID should appear on the `RoadEventFeature` object as an `id` property rather than the `road_event_id` property on the `RoadEvent`. 

Additionally using the `road_event_id` property on the `RoadEvent` should be deprecated (and the property eventually removed).

**Comment by DeraldDudley** [comment]
+1

**Comment by j-d-b** [comment]
Implemented in #146.
