### ISSUE TITLE
Allow GeoJSON Bounding Box on the WZDxFeed and RoadEventFeature objects

### ISSUE THREAD

**Issue by j-d-b** [usdot-jpo-ode/wzdx#142]
## Background
From the [GeoJSON specification section 5](https://tools.ietf.org/html/rfc7946#section-5):

> A GeoJSON object MAY have a member named "bbox" to include information on the coordinate range for its Geometries, Features, or FeatureCollections.... The "bbox" values define shapes with edges that follow lines of constant longitude, latitude, and elevation.

Currently, the WZDx schema defines custom FeatureCollection ([WZDxFeed](https://github.com/usdot-jpo-ode/jpo-wzdx/blob/master/spec-content/objects/WZDxFeed.md)) and Feature ([RoadEventFeature](https://github.com/usdot-jpo-ode/jpo-wzdx/blob/master/spec-content/objects/RoadEventFeature.md)) objects which are instances of the GeoJSON versions, but more restricted. They do not currently allow for the GeoJSON `bbox` property.

However, the geometry of a road event references the GeoJSON [MultiPoint](https://tools.ietf.org/html/rfc7946#section-3.1.3) and [LineString](https://tools.ietf.org/html/rfc7946#section-3.1.4) geometries for structure and thus `bbox` is allowed there.

## Proposed solution
Adding the optional `bbox` property to the `WZDxFeed` and `RoadEventFeature` would be a simple, backwards compatible change that would allow producers to specify a bounding box if desired and keeps WZDx closer to GeoJSON. This provides consistency with being able to provide it at the geometry level.

**Comment by DeraldDudley** [comment]
+1

**Comment by j-d-b** [comment]
Addressed in #145.
