### ISSUE TITLE
Allow specifying lane width via an optional `width` property on the Lane object

### ISSUE THREAD

**Issue by j-d-b** [usdot-jpo-ode/wzdx#156]
I'm not sure if producers have this data or if there is value, but allowing specifying the `width` of a lane has been thrown around in several subgroup discussions throughout the past year, so I wanted to ensure it was recorded on GitHub for discussion.

**Comment by vchandranNTAM** [comment]
While Lane width seems like a valuable add, characteristics of the lane belongs in the Asset layer. Tying this to the WorkZone events may muddy the waters. 

The WZDx discussion should focus on on what work is going on which roadway and which segment of it, where are the closures and whats going on now. 

Having said that WZDx efforts most definitely would fall into an extended TAMS strategy for DOTs and local agencies that own and manage transportation assets.

**Comment by j-d-b** [comment]
I agree with @vchandranNTAM and based on co-chairs discussion, all contributors are in agreement that properties like `width`, which apply to the base details of the area the road event occurs on rather than the changes due to the work zone, should not be covered by WZDx.
