### ISSUE TITLE
Clarify units for reduced_speed_limit

### ISSUE THREAD

**Issue by j-d-b** [usdot-jpo-ode/wzdx#169]
## Issue
The `reduced_speed_limit` property on the [RoadEvent](https://github.com/usdot-jpo-ode/wzdx/blob/master/spec-content/objects/RoadEvent.md) object is an Integer value defined only:

> The reduced speed limit posted within the event space.

*There is no mention of units.* As the `reduced_speed_limit` must be an Integer, it is not possible to include units within the value (e.g. `"35 mph"`). As WZDx moves towards including traffic data with the activities of the Smart Work Zone Subgroup, this needs to be addressed.

## Solutions
The following are several options for clarifying the units for `reduced_speed_limit`:

1. Include a recommendation in the text description that `reduced_speed_limit` should be in a certain unit, e.g. `mph`. This is non-binding but helps get things started and does not require an official specification change.
2. Require a certain unit for `reduced_speed_limit` specifically.
3. Add a property to the road event for `reduced_speed_limit_units` and associated new enumerated type `SpeedUnits`, to be used here and elsewhere as the spec expands.
4. Require a certain unit for all speed values in WZDx (which is only `reduced_speed_limit` now).
5. Allow specifying the units for speed in the `RoadEventFeedInfo` which applies to all information in the feed. This allows producers to choose at the top-level what unit their used in the feed information. An example implementation of this would be adding a new property `speed_units` to the `RoadEventFeedInfo`.

I have not yet checked what other standards do in regards to speed information units, but if WZDx is going to be expanded to include traffic information my first thought is that option 4. is the cleanest as it allows consumers to compare feeds from different producers easily without checking other fields for units and doing conversions.

**Comment by daylesworth** [comment]
@j-d-b, another variant of option 4 (and others) is to make the units property optional and specify a default value in the standard (probably "mph"). 

FYI, J2735 specifies speed limits as an integer in units of 0.02 m/s (probably not a good choice here). Google's Roads API has an optional "units" parameter that can be set to kph or mph (defaults to mph). OpenStreetMap includes the units in the maxspeed field only if it's not kph (e.g. "60" = 60 kph, "50 mph" = 50 mph).

**Comment by lynnerandolph** [comment]
As this is a standard, specifying the unit as part of the element would be my preference. We should try not to have consumers need to convert from one unit to the next depending on whose data they have.

Lynne

From: Jacob Brady ***@***.***>
Sent: Wednesday, April 14, 2021 2:52 PM
To: usdot-jpo-ode/wzdx ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [usdot-jpo-ode/wzdx] Clarify units for reduced_speed_limit (#169)

[EXTERNAL EMAIL]
Issue

The reduced_speed_limit property on the RoadEvent<https://urldefense.com/v3/__https:/github.com/usdot-jpo-ode/wzdx/blob/master/spec-content/objects/RoadEvent.md__;!!D-JDmu3Lc2wo0Jiybg!KXDlFMXGbrnUm_hr24eth7dacro066L_Sxbv5_KuO22hXWkEKMBL67A_mcHBMff3U68$> object is an Integer value defined as:

The reduced speed limit posted within the event space.

There is no mention of units and as the reduced_speed_limit must be an Integer, it is not possible to include units within the value (e.g. "35 mph"). As WZDx moves towards including traffic data with the activities of the Smart Work Zone Subgroup, this needs to be addressed.

Solutions

The following are several options for clarifying the units for reduced_speed_limit:

  1.  Include a recommendation in the text description that reduced_speed_limit should be in a certain unit, e.g. mph. This is non-binding but helps get things started and does not require an official specification change.
  2.  Require a certain unit for this field e.g. mph.
  3.  Add a property to the road event for reduced_speed_limit_units and associated new enumerated type SpeedUnits, to be used here and elsewhere as the spec expands.
  4.  Require a certain unit for all speed values in WZDx (which is only reduced_speed_limit now).
  5.  Allow specifying the units for speed in the RoadEventFeedInfo which applies to all information in the feed. This allows producers to choose at the top-level what unit their used in the feed information. An example implementation of this would be adding a new property speed_units to the RoadEventFeedInfo.

I have not yet checked what other standards do in regards to speed information units, but if WZDx is going to be expanded to include traffic information my first thought is that option 4. is the cleanest as it allows consumers to compare feeds from different producers easily without checking other fields for units and doing conversions.

-

**Comment by DeraldDudley** [comment]
Consider implementing #155 then add reduced_speed_limit to the Restrictions Class.

**Comment by j-d-b** [comment]
Based on some of the above comments and co-chairs discussion the preferred approach is to indicate that `reduced_speed_limit` must be in **miles per hour**.

**Comment by sergebeaudry** [comment]
If we want WZDx to become an international standard. the current suggestion will halt its adoption.  An alternative that cost nothing in the standard per say but effort on the data user is to define it as using the unit standardized at the defined location. 
EX: the roadevent is in USA = MPH,   From Canada= KPH.
  Would be nice to understand how the mapping/Automaker companies are managing the speed currently across the world.

**Comment by j-d-b** [comment]
Completed in #195.
