### ISSUE TITLE
Worker Presence: should it cover the presence of human beings, pieces of equipment, or both?

### ISSUE THREAD

**Issue by sergebeaudry** [usdot-jpo-ode/wzdx#173]
### Summary
The _RoadEvent_ object includes the _workers_present_ property that is currently a yes or no (Boolean) 
The current description is :  A flag indicating that there are workers present in the event space.

Some members of the Worker Presence working group have expressed that it may be preferable or easier to report the presence of on-site equipment, rather than or in addition to the presence of human beings.   For example, it may be desirable to report the real-time presence of trucks, smart arrow boards, or other pieces of Work Zone equipment. 
 
### Background
During the May 2021 Worker Presence sub-group meeting, some members expressed an interest in  including the reporting the real-time presence of work zone equipment.  The stated reason is that reporting equipment may be simpler and less fraught with legal concerns than reporting the presence of human beings.   Other members disagreed with this approach, saying reporting the presence of human beings is of particular import to data consumers who are building real-world applications, including automated driving systems--and that the presence of equipment and humans are not the same. 
The 2020 Worker Presence industry survey reflects that agencies have different perspectives on whether a worker should be considered present in various scenarios. 
Following is the question and answers related to that topic in the 2020 survey, most answers came from DOTs:

![2021_06_17_07_32_57_WZDX_WP_draft_issues_202106_Google_Docs](https://user-images.githubusercontent.com/54321625/122388917-58393c00-cf3e-11eb-92d0-c4076f92f096.png)

Unsurprisingly,  “Humans physically working within the work zone” was the most widely accepted definition (70% agreed), followed by “humans physically within the work zone but not working (e.g., on break) (65% agreed). However, the 3rd most popular response was “mobile equipment moving in the work zone” (57% agreed), suggesting that the presence of moving mobile equipment could be a proxy for the presence of human beings who are operating the equipment.
All the other potential definitions demonstrated less agreement among the respondents. 
 
### Proposal
WZDx is an open standard that will evolve over time.  It is generally preferable to start with incremental steps to encourage widespread adoption rather than seek to satisfy 100% of potential needs in advance of adoption. 

The WP subcommittee proposes that the _workers_present_ data structure remain **focused specifically on the presence of human beings rather than work zone equipment**. However, we suggest augmenting the workers_present data element with a property indicating the source of the data, which could include options such as:

- Self-report on mobile app
- Presence of maintenance vehicle
- Presence of arrow board
- etc.

### Discussion
This issue wants to collect your feedback on this subject and the proposed solution. 
Looking at the survey results and the overall goals of the WZDX project, please share your thoughts here on the issue and the proposed solution.

**Comment by vchandranNTAM** [comment]
I agree with the proposal to consider human beings as the primary factor that determines "Workers Present"

Also augmenting via other methods like arrow-boards can be helpful. An active arrow board for instance can be considered as potential signs of worker presence. 

Do we need to spell these augmented methods? How can this be "codified" into the spec in an open, vendor agnostic manner?

**Comment by DeraldDudley** [comment]
I would not mix people and equipment in the workers_present property.  Mixing data types is undesirable because its difficult to untangle them as the specification matures.  If its helpful to capture information about equipment then add a property or class for describing equipment.

**Comment by Nnageli** [comment]
Worker presence is great.  Presence of work zone equipment is important as well if they are equipped with IoT sensors to get real-time information. Maybe add property or class for it.

**Comment by sergebeaudry** [comment]
Thanks for your feedback.   it would be nice to see others potential enumerations for the human beings list.  Here a proposal including elements from the 2020 WP survey (Q:14 and Q:34)

- Self-report on mobile app
- Presence of maintenance vehicle
- Presence of smart arrow board
- Radio/phone
- Smart Wearable,   
- Camera
- Smart tools/devices: ex: a smart flagging baton, 

-Planned.  This one might not be 100% accurate but may be easy for many IOO to publish that workers shall be present.

What do you think?

**Comment by davidcraig4300** [comment]
Totally agree that this should revolve around actual humans working in the construction zone (not moving equipment).  My belief is, the goal should be to alert when there is a non protected human that is close to the moving vehicle, either on the drivable surface or very near the drivable surface (i.e. the shoulder).  Understanding when these conditions exist is critical to saving lives.

**Comment by sergebeaudry** [comment]
I would add to the list above:   Speed limit change.  in some state they change the speed limit when worker are present, this could be automated with Digital speed limit equipment.

Last check with the community if you see others sources for declaring worker presence. see the list above (2 post up)
Thanks

**Comment by j-d-b** [comment]
@sergebeaudry and @mark-mockett was this resolved in #206 or does more discussion need to happen?

**Comment by brookesc4** [comment]
I do not think that #206 address the equipment or personal topic.  I think this needs to be built in to have the ability to be added.  Down the road there are a lot of sensors and systems that can tie into a vehicle's beacon.  This could be the same for work equipment.  I think we would want to capture that.  The only other item that 206 doesn't cover is the type of person.  The main reason that would be needed is to show and highlight when someone is directing traffic via a traffic regulator, a worker that will be coming into the lane, or a worker that will be in and out of equipment.  

The worker activity and type could change the level of notification to the motorist.  Is the worker a surveyor, or someone mowing the grass?  Personal perform lawn maintenance on the shoulder inside the guardrails (as an example), pot hole patching were a person is walking in and out of the lane, is traffic control being placed or removed.  I know we may not need all of this break down but I think we should consider just more then yes / no on the workers.

**Comment by bzacimovic** [comment]
I think this should focus first on workers out of the vehicles because we could detect connected equipment in the future with me on and moving or operating.  I am working on this particular issue in Colorado. We are looking at some sort of homemade device with a cellular connection and an RFID chip reader to anonymously detect workers. We are not sure RFID is secure enough to do something like this. I think we start small with detecting workers in the work zone and then most to type or worker, in-or-out of vehicle, etc. with devices we have in the 2020 WP survey at first and then look at innovative solutions as they come in.  My question is what could we test NOW (this summer) to see how it works?

**Comment by sergebeaudry** [comment]
Thanks you all for the good comments,

Since the opening of this issue some changes happened:   
a)	Worker Presence element in the `WZDxFeed` now includes a `WorkerPresenceMethod` that could tie the worker presence to some equipment such as an arrowboard, maintenance vehicle, or smart location sensor.
b)	A new `SwzDeviceFeed` was created to publish information related to GPS enabled field devices

The addition of the new `SWZDeviceFeed` enables new possibilities for Worker Presence. That feed brings the potential to report in real-time information coming from GPS devices such as human wearables, vehicles, construction equipment.

The `SwzDeviceFeed` could be used as a source confirming the presence of worker on a stretch of road, which is the goal of the Worker Presence element in the `WZDXFeed`.
There will be some cross-over, but we should aim for complementarity between the 2 feeds instead of duplication.

Based on this discussion so far, the 2 feeds currently in place are a potential baseline to expand for the future to address those needs for more information on worker presence.

I’m recommending that the SWZ Device and Worker Presence subgroups meet and share ideas and propose some evolution in regards to Worker presence support that could be beneficial to the community.   

I recommend we close this issue #173 and let those 2 teams bring back new issues to discuss based on the outcome of their discussion.

**Comment by sergebeaudry** [comment]
the WorkerPresence and SWZ Field device subgroup co-chairs will start soon discussion on this subject and will create new issues on this subject.
I'm closing this issue
