### ISSUE TITLE
Add restriction-notice to the EventType Enumerated Type

### ISSUE THREAD

**Issue by DeraldDudley** [usdot-jpo-ode/wzdx#178]
# Add New Event Type:  `restriction-notice`

Adding a `restriction-notice` to the [EventType Enumerated Type](https://github.com/usdot-jpo-ode/wzdx/blob/master/spec-content/enumerated-types/EventType.md) enables State DOTs to warn drivers of hazardous restrictions such as low-clearances beneath bridges.

## Benefits
- Helps mitigate loss of life, personal injury, infrastructure damage, lost time and money, unnecessary emissions, and all the other ill effects of bridge and tunnel strikes.
- Fosters in-vehicle warnings about hazards to navigation.
- Establishes the WZDx specification can be leveraged to make transportation safer by extending it beyond its original purpose.
- Extending the specification may draw more agencies into using the Work Zone components of the specification.

## Costs
- Diversifying the specification is off scope.

## Support

- The New York State DOT has committed to developing a prototype feed.  
- Other State DOTs have expressed interests.
- Google and Here have committed to consuming and testing NYSDOT's feed
- The National States Geographic Information Council endorses the project.

## Example
- [An example of the `restriction-notice` EventType.](https://gist.github.com/DeraldDudley/b7d4271750cbeb0a91b2d438862ec729)

**Comment by j-d-b** [comment]
I like this addition. It is simple, backwards compatible, flexible, and allows using the WZDx model to represent any kind of restriction on the roadway.

Note a `restriction-notice` road event can represent a permanent restriction unrelated to road work or a work zone, such as reduced height due to an overhead structure, reduced width on a bridge, etc.

**Comment by j-d-b** [comment]
After the creation of #191 and spec extension subgroup meeting, it was decided that the restriction notice is better addressed in a new feed rather than the WZDxFeed, which should stay focused on work zones and similar or related road events (e.g. detour).

**Comment by DeraldDudley** [comment]
This should be contingent on issue #203

**Comment by j-d-b** [comment]
Completed by adding the [RoadRestrictionFeed](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/RoadRestrictionFeed.md) and [RestrictionRoadEvent](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/RestrictionRoadEvent.md) in #205 (WZDx v4.0).
