### ISSUE TITLE
Add road event-level dynamic traffic metrics

### ISSUE THREAD

**Issue by j-d-b** [usdot-jpo-ode/wzdx#187]
## Background
This issue seeks to start formal discussion regarding adding dynamic traffic metrics about the work zone road event to the road event object. This issue was created following initial discussion by the WZDx Smart Work Zones Subgroup.

WZDx is a format for disseminating real-time information about work zones to the public. In WZDx, a work zone is represented by one or more **road events**, which are geometries and details of a unit of work occurring on a roadway. As of v3.1, most of the properties of the road event are primarily static (`workers_present` is an exception, though its use is not yet clarified), such as geometry, start and end dates, and impact to traveling vehicles (e.g. lanes closed). 

The smart work zones subgroup intends to propose adding more dynamic information to the road event object to better represent its current state.

Examples of dynamic metrics are speed, volume, occupancy, and queue length. The example object that follows is from MassDOT's Vendor API Specification. This can be the basis for discussion of what dynamic traffic data members want to see added to the road event.

## MassDOT SWZM "Dynamic Metrics" Object Properties

Name | Type | Description | Conformance
-- | -- | -- | --
update_date | String; [date-time](https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-7.3.1) | The UTC time and date when the metrics were updated, in ISO 8601 format. | Required
volume | Number | Volume measured in vehicles per hour | Required
travel_time | Number | Travel time in seconds through the road event. As per TMDD “link-travel-time”. | Required
delay | Number | Delay in seconds through the road event. As per TMDD “link-delay”. | Optional
average_speed | Number | Average speed through the road event in KPH as per TMDD “link-speed-average”. | Required
capacity | Number | Capacity in vehicles-per-hour as per TMDD “link-capacity”. | Optional
speed_limit | Number | Free flow speed through the road event in KPH as per TMDD “link-speed-limit”. | Required
queue_length | Number | Length of queue formed upstream of the road event start location, specified in meters. | Optional
average_occupancy | Number | Average occupancy throughout the road event specified as a percent. | Optional

Note the above is not the proposal for what should be added to WZDx (especially conformance, I think all should be optional in whatever we propose), but an example of what could be added.

The above DynamicMetrics object could appear on the RoadEvent object as the value of a new optional property, `dynamic_traffic_data` (or similar).

## Next steps
1. What is the value to consumers of dynamic traffic data?
2. Is there any data in the above DynamicMetrics object that members do not want to see added (e.g. queue_length could be challenging to define consistently)?
3. Is there any data missing from the above DynamicMetrics object that would be beneficial to include (e.g. free flow travel time could be added)?

**Comment by Dunge** [comment]
Interesting. A few comments:

* `freeflow_time` can be computed from "travel_time - delay". Or vice-versa, the delay can be computed from travel_time and freeflow_time. But having all 3 could help reduce confusion.
* `speed_limit` is basically already part of the road_event object with `reduced_speed_limit`. Personally I would see the "normal" speed limit in the road_event object, while the "temporary reduced" speed limit that could be changed in the dynamic data. Just make sure we don't have duplicate fields representing the same thing.
* `capacity` is also something I don't think should be dynamic. Interesting value, but might be better placed at the road_event level. It's not something that changes every minutes.
* `average_speed`/`average_occupancy` doesn't have a time period range. Is it last minute, last hour, last day? I would follow the same period as the "volume", or even add a new field to define the time precision or these values.
* As you mention, `queue_length` is hard to define. Why select only upstream from the start location, why not count the length inside the workzone too? But then, what if you have multiple queues inside the workzone? It can also be imprecise, depending on the density of the sensors available.

**Comment by sergebeaudry** [comment]
Very good point mentionned by Dunge related to Speed_limit.   I would think that knowing the "normal" speed limit for that zone versus the "reduced" one may be useful for mapping/CAV consumer. So they can predict a time to travel based that will put more weight on current than historical or other sort of algorithms.    As both are part of the planning of a workzone I think they should stay as a road event at minimum.

**Comment by sergebeaudry** [comment]
This issue might need to be revisited.  Since then  a `TrafficSensor `object in `SWZDevicefeed `has been added to WZDx. Which covers real-time volume, occupancy, average speed.
 Some of the elements would be great addition to the `WZDxfeed `road event portion instead of the `SWZdevicefeed` ex: speed freeflow.
 An some others in eithers new object in the `SWZdevicefeed ` or in the `WZDXfeed  `  ex: travel time, delay...

**Comment by j-d-b** [comment]
Closed as this information isn't valuable to Work Zone Feed consumers and is aggregated data from multiple devices isn't able to be provided in a Device Feed.
