### ISSUE TITLE
Include explicit licensing information in the RoadEventFeedInfo

### ISSUE THREAD

**Issue by DeraldDudley** [usdot-jpo-ode/wzdx#19]
Consider including licensing information in the metadata.  Clearly define how the data can be used by consumers.  Is it open? Does it require attribution? Can it be used for commercial purposes?

**Comment by antrim** [comment]
Some data license provisions can limit broad use of the data. For example, some open licenses would not allow open data to mix with closed/proprietary datasets, which poses a significant limitation for how data can be utilized in web applications. At this early stage, it may be useful to recommend a few licenses for WZDx, or present a list of licenses with their implications. This is a useful primer on open data: https://opendefinition.org/guide/data/

**Comment by j-d-b** [comment]
Licensing information in the repository itself is also needed, perhaps in place of in metadata. GitHub has standardized the inclusion of a `LICENSE` or `LICENSE.md` file in the repository root.

**Comment by j-d-b** [comment]
Implemented in #157 and incorporated in the v3.1 release.
