### ISSUE TITLE
Replace beginning_accuracy and ending_accuracy with postional_accuracy.

### ISSUE THREAD

**Issue by DeraldDudley** [usdot-jpo-ode/wzdx#201]
# Replace beginning_accuracy and ending_accuracy with postional_accuracy.

The properties beginning_accuracy and ending_accuracy were established in version 1 of the specification before the adoption of GeoJSON.  They were important because it was thought a work zone would be located solely by a beginning point and and ending point.  The beginning_accuracy and ending_accuracy properties were essentially feature level metadata records established to build confidence in the spatial accuracy of the data.

With the adoption of GeoJson, features needs only one property to describe their accuracy.  The industry standard describes a feature's positional accuracy.  Here is the [FGDC Accuracy Standard](https://www.fgdc.gov/standards/projects/FGDC-standards-projects/accuracy/part3/chapter3).  This is a nice [Positional Accuracy resource from University of Minnesota](https://giscourses.cfans.umn.edu/sites/giscourses.cfans.umn.edu/files/nssda_handbook.pdf).

Proposed Changes...

1. In the RoadEvent feature;
- Drop beginning_accuracy 
- Drop ending_accuracy
- Insert positional_accuracy 
- Value of positional_accuracy is the PositionalAccuracy Object.

2. Change Spatial Verification enumeration to Positional Accuracy Object

## Positional Accuracy Object
The `PositionalAccuracy` object indicates the spatial accuracy of the feature.

### Properties
Property Name | Data Type | Description | Conformance | Notes
--- | --- | --- | --- | ---
`verification` | enumeration: estimated or verified | An indication of how the feature was defined. | Required | 
`accuracy` | real | A measure of the spatial accuracy | Optional  | This property sets the specification up nicely for measured accuracy.
`UnitOfMeasurement ` | enumeration: string | Unit the accuracy value represents | Optional | This property sets the specification up nicely for measured accuracy.

## Used By
Property | Object
--- | ---
`positional_accuracy` | [RoadEvent](/spec-content/objects/RoadEve

**Comment by DeraldDudley** [comment]
@j-d-b Can we close this one?

**Comment by j-d-b** [comment]
Closed following Spec Update Subgroup meeting on 2022-02-23.
