### ISSUE TITLE
Start End time probability

### ISSUE THREAD

**Issue by rdsheckler** [usdot-jpo-ode/wzdx#211]
There is value in associating a probability with the start end end time instead of or in addition to 'verified' or 'estimated'.  There will be work on predicting the start and end time of projects based upon equipment staging, weather, other associated projects, etc.  Having a field that gives some indication of the reliability of the start end and time allows for users to plan accordingly.  

Of course a project that is months or years off will have a low probability as will a weather dependent project with a bad weather forecast.  Likewise the pre-positioning of equipment may raise the probability of a start tomorrow to 80%.

**Comment by adam-graham-one-network** [comment]
This links closely to having a probability of the work zone being 'active' - having a real-time signal from a smart workzone being 100% and a long term planned work with no recent updates and only 5 minutes past the proposed start time having a low probability.

**Comment by j-d-b** [comment]
I think it is simpler to leave the probability calculation up to the consumer based on the information received in the feed, such as update dates, event dates compared to the current date, etc.

**Comment by j-d-b** [comment]
Closed due to lack of interest. @rdsheckler please re-open if needed.
