### ISSUE TITLE
Update Data Source Descriptions

### ISSUE THREAD

**Issue by sknick-iastate** [usdot-jpo-ode/wzdx#223]
Issue name: “Update data source descriptions to account for other feeds”
 ## Summary
As a note for the next update cycle, we may want to revisit the [Feed Data Source Object](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/FeedDataSource.md) descriptions to ensure they are also applicable for the smart work zone device feed (SwzDevice).  Most descriptions refer to work zone data or the authoritative/responsible source.  This could be general enough for the devices but could be clarified to provide more direction or guidance.

This isn't explicitly included anywhere but I think a business rule could also be established that the data source for devices should refer to the contractor performing the work and not the device manufacturer.  This will ensure that DOT or others consuming the data have direct contact to the contractor responsible for the device.

**Comment by tfoster-vm** [comment]
I would support knowing both the contractor and the data provider source. The reality is that most general contractors are responsible, but do not know much if anything about the data, thus the agency would still need to get to source of the information, thus having both may streamline the effort. I understand the contractual approach, but we often experience a different reality. Most contractors are happy to not get caught in the middle. My two cents.

**Comment by rdsheckler** [comment]
This is tangential, and I have said it before, but data source also needs to include information on data rights and ownership.  Otherwise the entire industry will fight this.
