### ISSUE TITLE
Add update_date specifically for location information

### ISSUE THREAD

**Issue by j-d-b** [usdot-jpo-ode/wzdx#236]
## Background

There is an `update_date` property several places in the specification: the [FeedInfo](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/FeedInfo.md), [FeedDataSource](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/FeedDataSource.md), [RoadEventCoreDetails](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/RoadEventCoreDetails.md), and [FieldDeviceCoreDetails](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/FieldDeviceCoreDetails.md).

In each object, the property is defined as: "The UTC date and time when the <object name> was last updated."

There are two issues with this:

1. It is not clear when the value should be updated (see #184).
2. It is not possible to know what changed.

Item 1. should be addressed by #184—this issue seeks to partially address 2. by proposing an update date specifically for location information.

This issue was spawned from subgroup member discussion specifically in regard to desire to know when the location (e.g. `geometry`, `road_names`) was updated. We do not want to add too much granularity to `update_date`—a specific `update_date` for each property is not necessary, but one for location may be desirable as this is arguably the most important features of a road event.

## Potential solutions

This could be accomplished by simply adding a new `location_update_date` property to the [RoadEventCoreDetails](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/RoadEventCoreDetails.md), and [FieldDeviceCoreDetails](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/FieldDeviceCoreDetails.md). It could be more complex, such as being added to a location-specific object similar to what is proposed in #233. 

## Drawbacks

While we want WZDx to meet the desires of producers and consumers and be powerful with optional properties to enable advances consumers to provide higher specificity, we also want to keep it simple and easy for new users to understand. Adding a new optional property to describe when location information was updated doesn't break backwards compatibility, but it does add complexity so it should be important to many consumers for clear reasons before it is implemented. This issue was created to ensure discussion was documented, as the concept of a "location update date" was brought up several separate times, but there it will not be prioritized until there is substantial demand. 

## Next Steps

- Determine if knowing when the location information of a road event or field device is still desired by consumers.
- Discuss and expand on possible implementations.

**Comment by j-d-b** [comment]
Closed due to lack of interest and not obvious benefit to users.

**Comment by rdsheckler** [comment]
We actually use this in our internal systems on a regular basis.  Location is one of those things that change when nothing else has changed.  Aside from updating the location with additional accuracy due to more constellations passing by there are real changes for moving work zones.  Such as, an arrow board that was used in a moving lane closure changes its location by the minute when nothing else has.
