### ISSUE TITLE
Problem with SwzFeed examples.

### ISSUE THREAD

**Issue by mdorford** [usdot-jpo-ode/wzdx#239]
Issue name: “[Clarification] — Version number in SwzFeed examples seems to be incorrect”
 ## Summary
Inside both JSON files of the https://github.com/usdot-jpo-ode/wzdx/tree/main/examples/SwzDeviceFeed files, the version number says '1.0' but it should read '4.0'  The RoadRestrictionFeed example does read 4.0
https://raw.githubusercontent.com/usdot-jpo-ode/wzdx/main/examples/RoadRestrictionFeed/bridge_height_restriction_linestring_example.geojson
 and
all three feeds in "4.0" use the same definition of FeedInfo
https://raw.githubusercontent.com/usdot-jpo-ode/wzdx/main/schemas/4.0/FeedInfo.json
    "version": {
      "description": "The WZDx specification version used to create the data feed, in 'major.minor' format"
Since it is the WZDx specification that is the version number (as opposed to the version number of the SwzFeed itself), I think it should be 4.0
 ## Motivation
For a program that can accept multiple versions of the WZDx specification and needs to differentiate between them, I have been using the version number as the way to differentiate.
 ## Proposed changes
The version number in arrow_board_ok_example.json and camera_error_example.json should be changed to 4.0

**Comment by j-d-b** [comment]
Thank you for noting this. I will address it shortly.
