### ISSUE TITLE
Alignment with OMF's Curb Data Spec

### ISSUE THREAD

**Issue by jlarsonOmahaNE** [usdot-jpo-ode/wzdx#241]
## Background
OMF recently released the [1.0.0 Curb Data Spec](https://github.com/openmobilityfoundation/curb-data-specification). Cities would be interested in identifying the overlap of a work zones and curb zones for better management in a local environment.
 ## Motivation
Local municipalities would like to identify when a work zone would interfere with vehicles being able to access a curb zone. This would help with vehicle congestion and safety in local downtowns/BIDs where delivery vehicles park in a travel lane when a work zone is present instead of going to the nearest open curb zone. It would be up to the data producer/consumer to update the necessary fields in their feeds depending on the overlap.
 ## Proposed changes
I would like to add an Optional field under `vehicle_impact` where the impacted curb zone ids can be referenced. See example below.

## Example

Name | Type | Description | Conformance | Notes
--- | --- | --- | --- | ---
`cds_impact` | Array  | The impact to CDS curb_zones from a work zone area. | Optional |

**Comment by jlarsonOmahaNE** [comment]
Moving this to a discussion

**Comment by jlarsonOmahaNE** [comment]
Reopening per Nate's [comment](https://github.com/openmobilityfoundation/curb-data-specification/pull/96#issuecomment-1177965619)

**Comment by natedeshmukhtowery** [comment]
Echoing my comment on the latest version of CDS, I think it would be useful to include an optional field for producers to indicate overlaps using CDS ids between wzdx events that impact curb areas

**Comment by schnuerle** [comment]
We've added a similar reference to WZDx from CDS here: https://github.com/openmobilityfoundation/curb-data-specification/pull/96

**Comment by j-d-b** [comment]
Implemented in v4.2.
