### ISSUE TITLE
Proposed update to RestrictionType.md

### ISSUE THREAD

**Issue by imcurtis** [usdot-jpo-ode/wzdx#256]
Adding several proposed values for road closures to the RestrictionType Enumerated Type so that there can be a central place where that information is stored and referenced from.

**Comment by j-d-b** [comment]
I'm not sure what is being proposed. Based on #255, it may help for you to check out [VehicleImpact](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/enumerated-types/VehicleImpact.md), which may be a better way to represent closures.

**Comment by imcurtis** [comment]
We are proposing adding values to RestrictionType which can give an explanation for why a road is closed (e.g. maintenance, seasonal, unspecified).

**Comment by DeraldDudley** [comment]
Alex, Jacob would like us to sett up an issue to host discussions.  Ill show you how.

**Comment by j-d-b** [comment]
@DeraldDudley, @imcurtis, this is the Issue. There is just not enough information about what is desired or proposed in the initial issue comment. Please expand on what you are proposing changing and the value of that change—thanks.

**Comment by j-d-b** [comment]
Closing as @DeraldDudley noted this will be address in a different manner, though a new issue and PR.
