### ISSUE TITLE
Allow specifying transport or deployed position for dynamic message signs

### ISSUE THREAD

**Issue by j-d-b** [usdot-jpo-ode/wzdx#274]
## Summary

This issue involves adding a property to the [DynamicMessageSign](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/DynamicMessageSign.md) object to enable producers of a [SwzDeviceFeed](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/SwzDeviceFeed.md) to specify if the message sign is in upright/deployed position or stowed/transport position.

## Background

This ability to specify transport vs upright already exists for the [ArrowBoard](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/ArrowBoard.md) through the `is_in_transport_position` property, which is a boolean defined as:

> A yes/no value indicating if the arrow board is in the stowed/transport position (`true`) or deployed/upright position (`false`).

## Proposed Solution

The proposed solution involves adding an `is_in_transport_position` property to the DynamicMessageSign object with the same description as used for the ArrowBoard.

**Comment by sergebeaudry** [comment]
I have no objection around that new property. However almost none of the DMS today have on board hardware to detect if they are up or down.  So this field shall be optional for now...  This will require a new generation of PCMS everywhere so it make time many years to get this mainstream.
  Smart arrow board are new in the market (just a few years) and that requirement was included in the original ENTERPRISE Transportation Pooled fund effort and by IOWA DOT. That is the reason almost all vendors are offering it.

**Comment by j-d-b** [comment]
Closing as discussion showed there are no companies currently providing this information. Feel free to reopen if it becomes relevant.
