### ISSUE TITLE
Specifying application of a device such as an arrow board

### ISSUE THREAD

**Issue by rdsheckler** [usdot-jpo-ode/wzdx#286]
Several of the device types that exist in WZDX can be used in a variety of applications.  Do we want to have specific applications?  

For instance, we have arrow boards that are mounted on trailers, service trucks, TMA trucks, striping trucks, sweepers, etc.  We track the application in our system and plan on passing that along in our feed with the assumption that the users will find value in these details.  Does WZDX want to put some standardization into these sort of specific applications, and can we suggest a short list of such applications?

**Comment by rdsheckler** [comment]
As an example, at iCone, some of the applications in which we see arrow boards deployed are:

•	Trailer
•	TMA, this encompasses a lot of applications, basically anything were a person is exposed should be in front of a TMA!
  o	"shadowing"
  o	cone deployment/retrieval
  o	pot hole patching
  o	crack filling
  o	guide rail repair
•	Plows and Salt trucks
•	Line painting
•	Street sweeping
•	Incident response ("Road Ranger", tow trucks, etc.)

**Comment by j-d-b** [comment]
Based on co-chairs discussion 2022-09-22, no consumers have expressed interest for this data. MassDOT noted they just need to know if a device (e.g. arrow board) is moving (FieldDeviceCoreDetails `is_moving`) and that there is an arrow board (marking a lane closure), not what the arrow board is mounted on.
