### ISSUE TITLE
Devices should only report facts as they are known - not interpret items such as 'road name'

### ISSUE THREAD

**Issue by rdsheckler** [usdot-jpo-ode/wzdx#287]
Philosophically we believe that in the process of monitoring devices it is important to only report to users the facts as measured/monitored on the device.  This is particularly true in the issue of reporting 'road name'.  

The 'road name' requires interpretation through associating a set of coordinates to a mathematical representation of a curve or string of points as well as correlating the resulting curve to a textual name recorded in a particular base map.  The specific base map that is used is a potential source of error.  The particular algorithm that is used for snapping to the curve is a potential source of error.  If the entity that writes the Device Feed performs the snapping to obtain the 'road name' then the accuracy of the 'road name' is hidden in the knowledge of the processes used.

We feel that the generator of the Device Feed should avoid processes that don't have defined accuracy and the consumer of the Device Feed should perform approximate processes for themselves so they can maintain an understanding of any inaccuracies that have been entered into the system.

This philosophy also informs our opinion that items like 'workers present' should only appear in the Device Feed when the specific device used is explicitly to announce 'workers present' and not as an interpretation that workers may be present because their is a truck with its flashers on.

**Comment by j-d-b** [comment]
Based on SWZ co-chairs discussion on 2022-04-20, the proposed change from this discussion/issue is that the `road_names` property on the [FieldDeviceCoreDetails](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/FieldDeviceCoreDetails.md) conformance should change from required to optional.

**Comment by j-d-b** [comment]
Resolved in #309.
