### ISSUE TITLE
Rename WZDxFeed to WorkZoneFeed (or similar)

### ISSUE THREAD

**Issue by j-d-b** [usdot-jpo-ode/wzdx#288]
This issue proposes renaming the [WZDxFeed](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/WZDxFeed.md) object to WorkZoneFeed.

## Background

WZDx v4.0 defines the following feeds:

- [WZDxFeed](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/WZDxFeed.md): describes high-level information about work zone events ocurring on roadways (called "road events") that impact the characteristics of the roadway and involve a change from the default state (such as a lane closure). This is the original work zone data exchange feed and the only feed that WZDx defined until [version 4.0](https://github.com/usdot-jpo-ode/wzdx/releases/tag/v4.0).
- [RoadRestrictionFeed](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/RoadRestrictionFeed.md): describes the location and details of restrictions on roadways.
- [SwzDeviceFeed](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/SwzDeviceFeed.md): describes information (location, status, live data) about field devices deployed on the roadway in work zones. (note this may be renamed to DeviceFeed as proposed in #242)

## Issue

There are several issues with the naming of WZDxFeed, mostly related to the name being confusing and only there for historical reasons:

- All feeds are WZDx feeds, so it is confusing to have one of the feeds named WZDxFeed
- Each of the feeds are WZDx feeds, so when referring to a feed out of context, it would be preceded by "WZDx". Thus, the WZDxFeed is the WZDx WZDxFeed
- The RoadRestrictionFeed and SwzDeviceFeed (to be DeviceFeed) provide indication of what the feed includes while the WZDxFeed is more general

## Proposed Change

- Rename the WZDxFeed to WorkZoneFeed

Then (assuming #242 is implemented) WZDx would define the following feeds:

- **WorkZoneFeed**: describes high-level information about work zone events occurring on roadways (called "road events") that impact the characteristics of the roadway and involve a change from the default state (such as a lane closure). This is the original work zone data exchange feed and the only feed that WZDx defined until [version 4.0](https://github.com/usdot-jpo-ode/wzdx/releases/tag/v4.0). It was previously called the "WZDxFeed".
- **RoadRestrictionFeed**: describes the location and details of restrictions on roadways.
- **DeviceFeed**: describes information (location, status, live data) about field devices deployed on the roadway, typically in work zones.

*Note that this is a rename of the feed object and feed as referenced throughout WZDx documentation and has no impact on the specification content or structure.*

**Comment by natedeshmukhtowery** [comment]
I highly support this change - it improves legibility and future proofing. Thanks!

**Comment by j-d-b** [comment]
Based on the WZDx Specification Update Subgroup Meeting on May 5, 2022, the rename to WorkZoneFeed will be implemented for WZDx v4.1.

**Comment by j-d-b** [comment]
Completed in #333
