### ISSUE TITLE
Add Static Text for Flashing Beacons

### ISSUE THREAD

**Issue by tfoster-vm** [usdot-jpo-ode/wzdx#295]
Add Static Text for Flashing Beacons: [New feature]
## Summary
Similar to #275 we need the same required field for the associated static text related to any Flashing Beacons to know what the reason/purpose is for the beacons flashing. What are they telling the motoring public? I know to make this a required field will have to wait until the next cycle for V5.0 of the spec/feed, but for this and #275 we should add them now as optional fields and make them required in the next cycle.
 ## Motivation
As of right now there is now way to know exactly what is being conveyed to the motorists, beyond a general function. The specific text will add this clarity.
## Proposed changes
I propose to make the associated static text an optional feed now and when v5.0 is accommodated in a future cycle, we then make it permanent, since we cannot not due to breaking backwards compatibility.

**Comment by devorah-ql** [comment]
This does seem like a good idea.  A general function (e.g. slow-traffic warnings etc) is different from a specific message (slow traffic 1 mile), and it makes sense to be able to provide the specific message.

**Comment by RHolt-RIDOT** [comment]
Many others have already well noted/described (e.g., via Issue #238) that there are many, many, many possible use cases for Flashing Beacons (FBs) in work zones, and while at first glance I was thinking @tfoster-vm and others have been 100% spot-on above in noting that that spec/feed ideally should accommodate/indicate the reason/purpose for (function of) the FB (i.e., what are they telling the road users?), as I think on it further, it may be helpful to remember the following:  per current MUTCD an FB is almost always SUPPLEMENTING an appropriate warning or regulatory sign, marker, or other TCD (_only exception I can think of is for an Intersection Control Beacon (ICB) where a Yellow FB need not be supplemented by anything else, and in vast vast vast majority of Work Zones there will NOT be any ICBs_).  So I suggest considering whether it makes sense to not focus on the FBs but instead focus on the "greater TCD" or system that each FB is associated with.  Not that anyone wants to see another list, but a 'high-end' generic list of such system functionality that I assume may be most commonly used in Work Zones in near future could be:

- Regulatory Speed Limit In Effect or Active (Regulatory)
- Advisory Speed Limit In Effect or Active (Warning Only)
- Warning, Road Worker(s) Ahead / Be Prepared to Stop or Slow As/If Necessary
- Warning, Traffic Queue or Congestion Ahead / Be Prepared to Stop or Slow As/If Necessary
- Warning, Adverse Weather Condition Detected / Be Prepared to Stop or Slow As/If Necessary
- Warning, New or Changed Traffic Pattern Ahead
- Warning (and/or Regulatory?), Over-Sized Vehicle Detected

I may certainly be missing a few from the above.

If more specific static text to specifically indicate what the TCD is telling road users is needed, then I can understand and am fully open to as proposed above by @tfoster-vm.  I just hope (from my DOT perspective) that, given there are so many, many possible messages on TTCDs that FBs can be used to supplement in a Work Zone, there won't be any undue burden on data providers/contractors (all the more support for making things "optional" at least for now).

**Comment by j-d-b** [comment]
Resolved in #308.
