### ISSUE TITLE
Report the velocity of equipment in mobile-operations

### ISSUE THREAD

**Issue by rdsheckler** [usdot-jpo-ode/wzdx#296]
We should be optionally reporting the speed of equipment that is moving.  Equipment speed is relevant to predicting where the work zone will be when the car arrives.

If the equipment has GPS technology built in then it also has the ability to generate speed.  That speed should be reported when possible.

**Comment by tfoster-vm** [comment]
@rdsheckler I respectfully disagree (at this point in time). This falls more into our walk before you run discussions and priorities. Trying to successfully predict where a pavement marking or maintenance vehicle will be next is often going to vary and not be consistently predictable. A pothole patching crew may stop randomly. Other may exit at the next ramp on a freeway vs proceeding. We need to report facts (your own words). What people do with the facts is up to users of the information. Some may predict where a crew will be when a vehicle approaches, but so far we have not heard much demand for this. 

This issue will at least provide others a chance for input. I welcome other opinions and healthy discussion.

**Comment by rdsheckler** [comment]
You're right the intermittent work zone is a particular problem.

**Comment by j-d-b** [comment]
Implemented in v4.2.
