### ISSUE TITLE
Allow "Point" for RoadEventFeatures

### ISSUE THREAD

**Issue by j-d-b** [usdot-jpo-ode/wzdx#297]
## Background

WZDx has always implied that a road event must include least a start and end coordinate, though it hasn't been technically required by the specification. 

Currently, the documentation for the [RoadEventFeature](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/RoadEventFeature.md) `geometry` property states:

> The Geometry object's type property MUST be [LineString](https://tools.ietf.org/html/rfc7946#section-3.1.4) or [MultiPoint](https://tools.ietf.org/html/rfc7946#section-3.1.3). LineString allows specifying the entire road event path and should be preferred. MultiPoint should be used when only the start and end coordinates are known.

The GeoJSON Point geometry is explicitly not allowed. However, there is nothing in the JSON schema limiting the number of positions (coordinate pairs) included for a LineString or MultiPoint, so technically including only one position is valid and has been used in practice.

## Proposed Change Options

1. Update the JSON schema to require at minimum that two positions are provided for LineString and MultiPoint. In addition, the description of the RoadEventFeature `geometry` should clearly state this. For cases where only a point location is known, producers can use the same lat/lon for both points in the coordinates array; OR
2. Remove the language about road events needing at least a start and end point and allow "Point" as a geometry type option for the RoadEventFeature.

**Comment by Dunge** [comment]
Is there a specific reason triggering this request? We see some validity in having an event reported with just a single point in case of very short road work or when the ending position is yet unknown (currently deploying equipment).

**Comment by rdsheckler** [comment]
The vast majority of road events will only be a single point for many years into the future.  It is just a reality that 85% of the work will be represented by an automated report from a truck with its flashers on or a smart arrow board.

**Comment by j-d-b** [comment]
Given the above comments, this issue can shift to discussion about adding [Point](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.2) geometry as an option for a [RoadEventFeature](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/RoadEventFeature.md).

**Comment by j-d-b** [comment]
Note that Option 1. is a breaking change as any RoadEventFeatures including only one position would no longer be valid.

**Comment by j-d-b** [comment]
Co-chairs discussion 2022-09-23 led to supporting the current implementation which emphasizes that road events should have at least a start and an end point. It is valid to include an event with a single lat/lon pair, but is not recommended.
