### ISSUE TITLE
Add inner- and outer-loop to Direction enumeration

### ISSUE THREAD

**Issue by mark-mockett** [usdot-jpo-ode/wzdx#324]
## Summary
"Inner Loop" and "Outer Loop" directions are included in the TMDD but were not added to WZDx previously for an unknown reason. This issue is to propose adding those values to the [Direction](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/enumerated-types/Direction.md) enumerated type. 

 ## Motivation
A couple states sign loop highways only as "Inner Loop" (for travel clockwise) or "Outer Loop" (for travel counter-clockwise). These two values are included in the TMDD but not in WZDx. It's cumbersome and inaccurate for those data producers to translate the direction of a road event occurring on one of these roads to conform to a north, south, east, or west direction, and may be unclear to data consumers when matching events to their maps. 

 ## Proposed changes
Add `inner-loop` and `outer-loop` to the [Direction](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/enumerated-types/Direction.md) enumerated type.

After the change (and pending addition of `unknown` and `undefined`), the Direction type could look like this:

Value | Description
--- | ---
`northbound`| Road flow is in the northbound direction
`eastbound` | Road flow is in the eastbound direction
`southbound` | Road flow is in the southbound direction
`westbound` | Road flow is in the westbound direction
`undefined` | Road flow does not have a signed direction. For a [RoadEventFeature](/spec-content/objects/RoadEventFeature.md), the first and last coordinates in the feature's geometry represent the beginning and end of the road event in the direction of travel it impacts.
`unknown` | 	Road flow may have a signed direction, but the affected direction of travel is not known
*NEW* `inner-loop` | Road flow is in the clockwise direction of a ring road or beltway..
*NEW* `outer-loop` | Road flow is in the counter-clockwise direction of a ring road or beltway.

**Comment by lynnerandolph** [comment]
![image](https://user-images.githubusercontent.com/59374820/199081251-e5862a43-a012-4bf0-a869-e7b509138f9e.png)

Also, I note that there is both a direction and an alignment--alignment is where the inner/outer is allowed.

**Comment by j-d-b** [comment]
Resolved in #356.
