### ISSUE TITLE
JSON schema validation fails for new WZDx v4.1 RoadEventCoreDetails directions

### ISSUE THREAD

**Issue by persjabari** [usdot-jpo-ode/wzdx#338]
Issue name: “Bug — JSON schema validation fails for new WZDx v4.1 RoadEventCoreDetails directions”
 ## Summary
Directions "unknown" and "undefined" in WZDx v4.1 fail to validate. This is because the definition of and reference to the old direction definition was not removed in v4.1. In https://github.com/usdot-jpo-ode/wzdx/blob/release/v4.1/schemas/4.1/RoadEventFeature.json#L354, the RoadEventCoreDetails direction references the old definition that is in a separate schema file. Meanwhile, the new direction definition defined at https://github.com/usdot-jpo-ode/wzdx/blob/release/v4.1/schemas/4.1/RoadEventFeature.json#L555 appears to be unused. 
 ## Proposed changes
The old direction definition and references to it need to be removed in favor of the new direction definition.

**Comment by mark-mockett** [comment]
Thanks for catching that @persjabari - we'll make the fix in the `fixes/release-v4.1` branch, which is where we're making final fixes for the v4.1 release.

**Comment by j-d-b** [comment]
Resolved in #335
