### ISSUE TITLE
Reconsider and clarify Flashing Beacon

### ISSUE THREAD

**Issue by j-d-b** [usdot-jpo-ode/wzdx#341]
## Background

The WZDx specification defines a [FlashingBeacon](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/FlashingBeacon.md) object that is defined as:

> a flashing beacon light of any form (e.g. trailer-mounted, vehicle), used to indicate something and capture driver attention.

There has been confusion about what specific devices are considered to be a flashing beacon, especially when looking at the [MUTCD](https://mutcd.fhwa.dot.gov/htm/2009/part4/part4l.htm) which defines categories of flashing beacons. Some types of flashing beacons in MUTCD are not applicable here, such as intersection control beacons or stop beacons. 

Some producers have considered anything with flashing lights (such as a work truck) to be represented with a flashing beacon; other ideas are that the flashing beacon should be for conditional impacts, such as a "Vehicles Entering" sign where the condition is only active when the lights are flashing.

## Solution

The specification documentation should clarify when the flashing beacon should be used.

Possible producer use cases of devices with flashing lights should be discussed and determined which are "flashing beacons" and how to represent those that are not (e.g. with a [Location Marker](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/LocationMarker.md)).

It's possible that the Flashing Beacon object should be renamed to be more specific and possibly reference a concept defined in MUTCD (such as flashing warning beacon).

**Comment by NeilBoudreau** [comment]
There is some confusion between how we have defined a “Flashing Beacon” in the Device Feed and how the practitioners in the field are actually utilizing the device.  We want to ensure that we are following the MUTCD definition of a “Flashing Warning Beacon” that is used in a temporary work zone environment versus a permanent condition.  To address this in the most simplistic way, I propose a modification to the text that is used to describe the Flashing Beacon Object as follows:

Current: The FlashingBeacon object describes a flashing beacon light of any form (e.g. trailer-mounted, vehicle), used to indicate something and capture driver attention.

Proposed: The FlashingBeacon object describes a flashing warning beacon used to supplement a temporary traffic control device, mounted on a sign or channelizing device that are used to indicate a warning condition and capture driver attention.

**Comment by j-d-b** [comment]
Thank you @NeilBoudreau, I will make a PR updating the description of [FlashingBeacon](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/FlashingBeacon.md).

**Comment by j-d-b** [comment]
Resolved in #354.
