### ISSUE TITLE
WorkersPresent Data Field 

### ISSUE THREAD

**Issue by Mahsa-Ettefagh** [usdot-jpo-ode/wzdx#39]
Based on WZDx Workshop participants, construction workers can benefit from data that puts them “on the map,” making them visible in work  zones,  which  can  be  high-risk  environments.  In  addition,  participants  noted  that  these workers  can  provide  real-time,  on-the-ground  information  to  make  work  zone  data  more complete  and  useful  as  a  tool  for  improving  safety.  Incorporating  this  information  about  work zones  into  navigation  apps  and  consumer  maps  can  alert  drivers  to  reduce  speed  and  signal  to AVs to transfer control to a human driver ahead of time.

Solution: Make WorkersPresent data field changed from "Optional" to "Required" in the next version of the specification

**Comment by sknick-iastate** [comment]
In Iowa this isn't something we currently collect.  I don't know of any good large scale solutions currently available to get this data either.  I have heard limited type deployments.  

So  I am very hesitant to make this required because I feel the options at least in Iowa and some other states would be to say workers are present all of the time or just not produce a WZDx because they can't provide all of the required data.

I agree it is very important information to have and collect but don't know the capability in providing this yet.

**Comment by sergebeaudry** [comment]
I agree that this is a very important information going forward. This also goes well with initive to change speed in work zone when workers present. 
I would suggest that this information is added to the current revision with an "optional" status.  This will show the importance going FWD and will help the market to adjust.  in a V.3 then the status might become "required".

**Comment by sergebeaudry** [comment]
worker present is also defined in the data dictionary [https://collaboration.fhwa.dot.gov/wzmp/Data%20DictionaryDocuments/WZAD%20Data%20Dictionary_VERSION%202.pdf](url)  table 6, element 135 on page 40.

**Comment by CraigMoore-Sea** [comment]
We need some clarity on what this represents:
1) workers on site in the work zone; which has issues already explained in this thread
2) workers in the roadway, such as flagger, uniformed police officers, etc. These may be outside the work zone contained by traffic control devices. I see more value in communicating number 2.

Regardless, this is information that most urban jurisdiction won't be able to provide so if we make it required we will need to have a unknown value, at which point it's not really much different than being optional.

**Comment by Mahsa-Ettefagh** [comment]
**Comment from Charlotte Tao from Lyft** - Worker presence data would be particularly valuable for autonomous driving for two reasons:

1 - One is for safety purposes. Autonomous vehicles should detect workers present at work zones and should either slow down or switch to manual driving mode completely. In cases when perception fails to detect workers, vehicles are expected to rely on an offline dataset as the baseline and still slow down or switch to manual mode if necessary.

2 - The other is for machine learning purposes. Having the dataset will certainly help train and validate perception models for detecting work zones and workers. There will be no better way to collect the ground truth for data like this.

**Comment by lynnerandolph** [comment]
A boolean seems to be difficult for this field. There's no way to say "we don't know if workers are present", which is probably the case most of the time. It could become an enumeration which adds "Unknown" to the list with present and not present.

**Comment by davidcraig4300** [comment]
Thinking more about this.  I see this as a very valuable item for Automated Driving (hands free driving like a SAE Level 2, 3, or even 4 vehicle).  Basically, these vehicles could use this information to hand back driving to the human when before entering a Work Zone that has workers present.  I could even see this at some point becoming a requirement.  This could be transmitted to the vehicle either V2V/V2X or even possibly through the mapping companies adding this data to the traffic dynamic layer of the navigation maps.  These Automated driving systems should already have some connection between navigation and the Automated Driving system, so this could be a simple input added to the escalation process of handing back control to the human.

**Comment by j-d-b** [comment]
Partial resolution in #206, implemented in WZDx v4.0. 

For further suggestions for handling worker presence, create a new issue.
