### ISSUE TITLE
Exit lane type enumerations

### ISSUE THREAD

**Issue by sknick-iastate** [usdot-jpo-ode/wzdx#5]
In Iowa we are trying to map our standard closure types to the lane enumerations for both the open and closed lanes.  We are not exactly sure when and how to use the exit ramp laneType enumerations from Table 7 in the specification (left-exit-ramp, right-exit-ramp, right-second-exit-ramp, etc).  Without a definition it is hard to determine if these should only be used when the roadway is a ramp or is this to be used for dedicated exit lanes (not treat them as through lanes).  Some more definitions, descriptions, or examples of these would be beneficial.

**Comment by lynnerandolph** [comment]
I think if the lane index is used instead, you could just number the lanes in a consistent manner and say if they are exit or mainlane or HOV or express or shoulder.
