### ISSUE TITLE
Technical Support for is_architectural_change

### ISSUE THREAD

**Issue by Polly-Okunieff** [usdot-jpo-ode/wzdx#96]
In the current version, a feed issuer can submit more than one work type. So one work type may designate an architecture change to a work type, while the other may not.  This may be true, but there will be confusion. Also, is maintenance ever an architectural change? by definition, it is just fixing or preserving existing infrastructure.  This may require guidance and best practices discussion.

**Comment by j-d-b** [comment]
This likely ties into #78. That is, a change in work type should be one of the fields that causing breaking the work area into multiple road events. If this is the case we'd allow just one work type and is architectural change per event. This may be the clearest method, if there is never a case where two distinct types of work are occurring at the same time on the same piece of roadway.
